name: livewell_test
description: LiveWell flutter test

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ./core
    
  connectivity_plus: 3.0.3
  cupertino_icons: 1.0.2
  dio: 5.0.1
  flutter_dotenv: 5.0.2
  flutter_hooks: 0.18.6
  gallery_saver: 2.3.2
  get_it: 7.2.0
  hooks_riverpod: 2.2.0
  path_provider: 2.0.13
  permission_handler: 10.2.0
  visibility_detector: 0.3.3


dev_dependencies:
    build_runner: 2.3.2
    flutter_lints: 1.0.4
    flutter_test:
      sdk: flutter
    mockito: 5.3.2

flutter:
  uses-material-design: true
  assets:
    - .env

